USE university_health_clinic;
		   
INSERT INTO lab_test (test_name, test_description) VALUES 
("Complete Blood Count (CBC)", "This test evaluates the types and numbers of cells in the blood, including red blood cells, white blood cells, and platelets."),
("Blood Chemistry Panel", "This test checks levels of different chemicals and electrolytes in the blood, including glucose, sodium, potassium, calcium, and others."),
("Lipid Profile", "This test measures levels of different types of cholesterol and triglycerides in the blood, which can be useful in assessing cardiovascular risk."),
("Liver Function Tests", "These tests evaluate the health and function of the liver, including levels of enzymes and proteins that are produced by the liver."),
("Kidney Function Tests", "These tests evaluate the health and function of the kidneys, including levels of waste products like creatinine and blood urea nitrogen (BUN)."),
("Thyroid Function Tests", "These tests measure levels of thyroid hormones in the blood, which can help diagnose conditions like hypothyroidism or hyperthyroidism."),
("Urinalysis", "This test examines a sample of urine to evaluate kidney function, identify infections, and detect other potential health problems."),
("Stool Analysis", "This test examines a sample of stool to evaluate digestive health and identify potential problems like infections or inflammation."),
("Pap Smear", "This test is used to screen for cervical cancer in women, by examining cells collected from the cervix."),
("Biopsy", "This test involves the removal of a small tissue sample for examination under a microscope, to diagnose or monitor conditions like cancer or infections."),
("Electrocardiogram (ECG)", "This test records the electrical activity of the heart to evaluate heart health and diagnose conditions like arrhythmias or heart attacks."),
("Spirometry", "This test measures lung function by evaluating the volume of air a person can inhale and exhale, which can help diagnose conditions like asthma or chronic obstructive pulmonary disease (COPD)."),
("Blood Coagulation Tests", "These tests measure how quickly the blood clots and can be used to diagnose conditions like bleeding disorders or monitor treatment with blood-thinning medications."),
("Allergy Tests", "These tests evaluate the immune system's response to allergens and can help diagnose conditions like food allergies or allergic rhinitis."),
("Serology Tests", "These tests evaluate the presence of antibodies in the blood and can be used to diagnose infections like HIV, hepatitis, or Lyme disease."),
("Imaging Tests", "These tests, such as X-rays, CT scans, or MRIs, use different technologies to visualize internal organs or tissues and diagnose conditions like fractures, tumors, or infections."),
("Genetic Testing", "This test examines DNA to evaluate the risk of inherited disorders, diagnose genetic conditions, or identify genetic mutations that may impact treatment options."),
("Hormone Tests", "These tests evaluate the levels of hormones in the blood, which can help diagnose conditions like diabetes, thyroid disorders, or reproductive disorders."),
("Bone Density Tests", "These tests evaluate the density and strength of bones, which can help diagnose osteoporosis or assess the risk of fractures."),
("Drug Screening Tests", "These tests evaluate the presence of drugs or their metabolites in the blood, urine, or hair, which can be used to diagnose drug abuse or monitor compliance with medication regimens."),
("Fecal Occult Blood Test", "This test checks for the presence of blood in the stool, which can indicate gastrointestinal bleeding or colon cancer."),
("Vitamin and Mineral Tests", "These tests evaluate the levels of vitamins and minerals in the blood, which can help diagnose deficiencies or excesses that may impact overall health"),
("Arterial Blood Gas (ABG)", "This test evaluates the levels of oxygen, carbon dioxide, and other gases in the blood, which can help diagnose respiratory or metabolic disorders."),
("C-reactive Protein (CRP)", "This test measures levels of a protein in the blood that is produced in response to inflammation, which can help diagnose infections or autoimmune disorders."),
("Erythrocyte Sedimentation Rate (ESR)", "This test measures the rate at which red blood cells settle in a test tube, which can be an indicator of inflammation or infection."),
("Hemoglobin A1C (HbA1C)", "This test measures the average level of blood sugar over the past two to three months and is used to diagnose and monitor diabetes."),
("Prothrombin Time (PT) and International Normalized Ratio (INR)", "These tests evaluate the blood's ability to clot and are used to diagnose bleeding disorders or monitor treatment with blood-thinning medications."),
("Lactate Dehydrogenase (LDH)", "This test measures levels of an enzyme in the blood that is produced by cells throughout the body and can be elevated in conditions like heart attack, liver disease, or cancer."),
("Troponin", "This test measures levels of a protein in the blood that is released when heart muscle is damaged, which can be useful in diagnosing heart attacks."),
("Therapeutic Drug Monitoring (TDM)", "This test evaluates the levels of certain medications in the blood, to ensure that they are at the appropriate level to be effective and safe."),
("Amniocentesis", "This test involves the removal of a small sample of amniotic fluid for examination, to diagnose genetic disorders or other potential health problems in the developing fetus."),
("Chorionic Villus Sampling (CVS)", "This test involves the removal of a small sample of placental tissue for examination, to diagnose genetic disorders or other potential health problems in the developing fetus."),
("Ultrasound", "This test uses sound waves to produce images of internal organs or tissues, and can be used to diagnose conditions like pregnancy, gallstones, or tumors."),
("Mammography", "This test uses X-rays to produce images of the breast tissue, to screen for breast cancer or diagnose breast problems."),
("Colonoscopy", "This test involves the insertion of a flexible tube with a camera into the colon, to visualize and diagnose potential problems like polyps or cancer."),
("Endoscopy", "This test involves the insertion of a flexible tube with a camera into the digestive tract, to visualize and diagnose potential problems like ulcers or inflammation.");

