USE university_health_clinic;

INSERT INTO qualification (abbreviation, name) VALUES ('MD', 'Doctor of Medicine');
INSERT INTO qualification (abbreviation, name) VALUES ('DO', 'Doctor of Osteopathic Medicine');
INSERT INTO qualification (abbreviation, name) VALUES ('DMD', 'Doctor of Dental Medicine');
INSERT INTO qualification (abbreviation, name) VALUES ('DDS', 'Doctor of Dental Surgery');
INSERT INTO qualification (abbreviation, name) VALUES ('DPM', 'Doctor of Podiatric Medicine');
INSERT INTO qualification (abbreviation, name) VALUES ('DVM', 'Doctor of Veterinary Medicine');
INSERT INTO qualification (abbreviation, name) VALUES ('OD', 'Doctor of Optometry');
INSERT INTO qualification (abbreviation, name) VALUES ('BSN', 'Bachelor of Science in Nursing');
INSERT INTO qualification (abbreviation, name) VALUES ('MSN', 'Master of Science in Nursing');
INSERT INTO qualification (abbreviation, name) VALUES ('DNP', 'Doctor of Nursing Practice');
INSERT INTO qualification (abbreviation, name) VALUES ('PharmD', 'Doctor of Pharmacy');
INSERT INTO qualification (abbreviation, name) VALUES ('PA', 'Physician Assistant');
INSERT INTO qualification (abbreviation, name) VALUES ('CNM', 'Certified Nurse Midwife');
INSERT INTO qualification (abbreviation, name) VALUES ('DPT', 'Doctor of Physical Therapy');
INSERT INTO qualification (abbreviation, name) VALUES ('OTD', 'Doctor of Occupational Therapy');
INSERT INTO qualification (abbreviation, name) VALUES ('AuD', 'Doctor of Audiology');
INSERT INTO qualification (abbreviation, name) VALUES ('DC', 'Doctor of Chiropractic');
INSERT INTO qualification (abbreviation, name) VALUES ('ND', 'Doctor of Naturopathic Medicine');
INSERT INTO qualification (abbreviation, name) VALUES ('PsyD', 'Doctor of Psychology');
INSERT INTO qualification (abbreviation, name) VALUES ('DSW', 'Doctor of Social Work');
